"""
File download utilities for retrieving files generated by Claude skills.

Adapted from anthropics/claude-cookbooks.

Use this to download PDFs, Excel files, PowerPoint decks, and other documents
that Claude generates via built-in skills (xlsx, pptx, pdf, docx).

Usage:
    from utils.file_utils import download_all_files, print_download_summary

    response = client.beta.messages.create(...)
    results = download_all_files(client, response, output_dir="output")
    print_download_summary(results)
"""

import json
import os
import re
from pathlib import Path
from typing import Any

from anthropic import Anthropic


def extract_file_ids(response) -> list[str]:
    """Extract all file IDs from a Claude API response."""
    file_ids = []
    for block in response.content:
        if block.type == "bash_code_execution_tool_result":
            try:
                if hasattr(block, "content") and hasattr(block.content, "content"):
                    for item in block.content.content:
                        if hasattr(item, "file_id"):
                            file_ids.append(item.file_id)
            except Exception as e:
                print(f"Warning: Error parsing bash_code_execution_tool_result: {e}")
                continue
        elif block.type == "tool_result":
            try:
                if hasattr(block, "output"):
                    output_str = str(block.output)
                    if "file_id" in output_str.lower():
                        try:
                            output_json = json.loads(output_str)
                            if isinstance(output_json, dict) and "file_id" in output_json:
                                file_ids.append(output_json["file_id"])
                            elif isinstance(output_json, list):
                                for item in output_json:
                                    if isinstance(item, dict) and "file_id" in item:
                                        file_ids.append(item["file_id"])
                        except json.JSONDecodeError:
                            pattern = r"file_id['\"]?\s*[:=]\s*['\"]?([a-zA-Z0-9_-]+)"
                            matches = re.findall(pattern, output_str)
                            file_ids.extend(matches)
            except Exception as e:
                print(f"Warning: Error parsing tool_result block: {e}")
                continue
    seen = set()
    unique_file_ids = []
    for fid in file_ids:
        if fid not in seen:
            seen.add(fid)
            unique_file_ids.append(fid)
    return unique_file_ids


def download_file(client: Anthropic, file_id: str, output_path: str, overwrite: bool = True) -> dict[str, Any]:
    """Download a single file by its file ID."""
    result = {"file_id": file_id, "output_path": output_path, "size": 0, "success": False, "error": None}
    try:
        file_exists = os.path.exists(output_path)
        if file_exists and not overwrite:
            result["error"] = f"File already exists: {output_path} (set overwrite=True to replace)"
            return result
        output_dir = os.path.dirname(output_path)
        if output_dir:
            Path(output_dir).mkdir(parents=True, exist_ok=True)
        file_content = client.beta.files.download(file_id=file_id)
        with open(output_path, "wb") as f:
            f.write(file_content.read())
        result["size"] = os.path.getsize(output_path)
        result["success"] = True
        result["overwritten"] = file_exists
    except Exception as e:
        result["error"] = str(e)
    return result


def download_all_files(
    client: Anthropic, response, output_dir: str = "outputs", prefix: str = "", overwrite: bool = True
) -> list[dict[str, Any]]:
    """Download all files from a Claude API response."""
    file_ids = extract_file_ids(response)
    results = []
    for i, file_id in enumerate(file_ids, 1):
        try:
            file_info = client.beta.files.retrieve_metadata(file_id=file_id)
            filename = file_info.filename
        except Exception:
            filename = f"file_{i}.bin"
        if prefix:
            filename = f"{prefix}{filename}"
        output_path = os.path.join(output_dir, filename)
        result = download_file(client, file_id, output_path, overwrite=overwrite)
        results.append(result)
    return results


def get_file_info(client: Anthropic, file_id: str) -> dict[str, Any] | None:
    """Get metadata about a file."""
    try:
        file_info = client.beta.files.retrieve_metadata(file_id=file_id)
        return {
            "file_id": file_info.id,
            "filename": file_info.filename,
            "size": file_info.size_bytes,
            "mime_type": file_info.mime_type,
            "created_at": file_info.created_at,
            "type": file_info.type,
            "downloadable": file_info.downloadable,
        }
    except Exception as e:
        print(f"Error retrieving file info: {e}")
        return None


def print_download_summary(results: list[dict[str, Any]]) -> None:
    """Print a summary of downloaded files."""
    print("\nFile Download Summary")
    print("=" * 50)
    success_count = 0
    total_size = 0
    for result in results:
        if result["success"]:
            size_kb = result["size"] / 1024
            overwrite_notice = " [overwritten]" if result.get("overwritten", False) else ""
            print(f"  {result['output_path']} ({size_kb:.1f} KB){overwrite_notice}")
            success_count += 1
            total_size += result["size"]
        else:
            print(f"  FAILED: {result['output_path']} - {result['error']}")
    print(f"\nTotal: {success_count}/{len(results)} files downloaded")
    if success_count > 0:
        total_mb = total_size / (1024 * 1024)
        print(f"Total size: {total_mb:.2f} MB")
